/**
 * generated by Xtext 2.32.0
 */
package my.xtext.featurelist.myfeaturelist.myFeatureList;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link my.xtext.featurelist.myfeaturelist.myFeatureList.AttributeProperty#getAttribute <em>Attribute</em>}</li>
 * </ul>
 *
 * @see my.xtext.featurelist.myfeaturelist.myFeatureList.MyFeatureListPackage#getAttributeProperty()
 * @model
 * @generated
 */
public interface AttributeProperty extends Property
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(Attribute)
   * @see my.xtext.featurelist.myfeaturelist.myFeatureList.MyFeatureListPackage#getAttributeProperty_Attribute()
   * @model
   * @generated
   */
  Attribute getAttribute();

  /**
   * Sets the value of the '{@link my.xtext.featurelist.myfeaturelist.myFeatureList.AttributeProperty#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(Attribute value);

} // AttributeProperty
