/**
 * generated by Xtext 2.32.0
 */
package my.xtext.featurelist.myfeaturelist.myFeatureList;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Concept Property</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see my.xtext.featurelist.myfeaturelist.myFeatureList.MyFeatureListPackage#getConceptProperty()
 * @model
 * @generated
 */
public interface ConceptProperty extends Property
{
} // ConceptProperty
