/*
 * generated by Xtext 2.32.0
 */
package xtext.featurelanguage.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFeatureLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(xtext.featurelanguage.featureLanguage.FeatureLanguagePackage.eINSTANCE);
		return result;
	}
}
