/*
 * generated by Xtext 2.32.0
 */
package my.xtext.featurelist.myfeaturelist.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyFeatureListScopeProvider extends DelegatingScopeProvider {
}
