/*
 * generated by Xtext 2.32.0
 */
package my.xtext.featurelist.myfeaturelist.parser.antlr;

import com.google.inject.Inject;
import my.xtext.featurelist.myfeaturelist.parser.antlr.internal.InternalMyFeatureListParser;
import my.xtext.featurelist.myfeaturelist.services.MyFeatureListGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyFeatureListParser extends AbstractAntlrParser {

	@Inject
	private MyFeatureListGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyFeatureListParser createParser(XtextTokenStream stream) {
		return new InternalMyFeatureListParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FeatureList";
	}

	public MyFeatureListGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyFeatureListGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
