/**
 * generated by Xtext 2.32.0
 */
package xtext.featurelanguage.featureLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import xtext.featurelanguage.featureLanguage.ConceptProperty;
import xtext.featurelanguage.featureLanguage.FeatureLanguagePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Concept Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConceptPropertyImpl extends PropertyImpl implements ConceptProperty
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConceptPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FeatureLanguagePackage.Literals.CONCEPT_PROPERTY;
  }

} //ConceptPropertyImpl
