/*
 * generated by Xtext 2.32.0
 */
package my.xtext.featurelist.myfeaturelist.serializer;

import com.google.inject.Inject;
import java.util.Set;
import my.xtext.featurelist.myfeaturelist.myFeatureList.Concept;
import my.xtext.featurelist.myfeaturelist.myFeatureList.Feature;
import my.xtext.featurelist.myfeaturelist.myFeatureList.FeatureList;
import my.xtext.featurelist.myfeaturelist.myFeatureList.MyFeatureListPackage;
import my.xtext.featurelist.myfeaturelist.services.MyFeatureListGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class MyFeatureListSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyFeatureListGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyFeatureListPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyFeatureListPackage.CONCEPT:
				sequence_Concept(context, (Concept) semanticObject); 
				return; 
			case MyFeatureListPackage.FEATURE:
				sequence_Feature(context, (Feature) semanticObject); 
				return; 
			case MyFeatureListPackage.FEATURE_LIST:
				sequence_FeatureList(context, (FeatureList) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Concept returns Concept
	 *
	 * Constraint:
	 *     (name=ID attributes+=Concept)
	 * </pre>
	 */
	protected void sequence_Concept(ISerializationContext context, Concept semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     FeatureList returns FeatureList
	 *
	 * Constraint:
	 *     ((concept+=Concept+ feature+=Feature+) | feature+=Feature+)?
	 * </pre>
	 */
	protected void sequence_FeatureList(ISerializationContext context, FeatureList semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Feature returns Feature
	 *
	 * Constraint:
	 *     (name=ID verb=Verb concept=Concept)
	 * </pre>
	 */
	protected void sequence_Feature(ISerializationContext context, Feature semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyFeatureListPackage.Literals.FEATURE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyFeatureListPackage.Literals.FEATURE__NAME));
			if (transientValues.isValueTransient(semanticObject, MyFeatureListPackage.Literals.FEATURE__VERB) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyFeatureListPackage.Literals.FEATURE__VERB));
			if (transientValues.isValueTransient(semanticObject, MyFeatureListPackage.Literals.FEATURE__CONCEPT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyFeatureListPackage.Literals.FEATURE__CONCEPT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFeatureAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFeatureAccess().getVerbVerbEnumRuleCall_2_0(), semanticObject.getVerb());
		feeder.accept(grammarAccess.getFeatureAccess().getConceptConceptParserRuleCall_3_0(), semanticObject.getConcept());
		feeder.finish();
	}
	
	
}
