/**
 * generated by Xtext 2.32.0
 */
package xtext.featurelanguage.featureLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.featurelanguage.featureLanguage.Constraint#getConcept <em>Concept</em>}</li>
 *   <li>{@link xtext.featurelanguage.featureLanguage.Constraint#getCharacteristic <em>Characteristic</em>}</li>
 *   <li>{@link xtext.featurelanguage.featureLanguage.Constraint#getCondition <em>Condition</em>}</li>
 *   <li>{@link xtext.featurelanguage.featureLanguage.Constraint#getErrormsg <em>Errormsg</em>}</li>
 * </ul>
 *
 * @see xtext.featurelanguage.featureLanguage.FeatureLanguagePackage#getConstraint()
 * @model
 * @generated
 */
public interface Constraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Concept</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concept</em>' reference.
   * @see #setConcept(Concept)
   * @see xtext.featurelanguage.featureLanguage.FeatureLanguagePackage#getConstraint_Concept()
   * @model
   * @generated
   */
  Concept getConcept();

  /**
   * Sets the value of the '{@link xtext.featurelanguage.featureLanguage.Constraint#getConcept <em>Concept</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concept</em>' reference.
   * @see #getConcept()
   * @generated
   */
  void setConcept(Concept value);

  /**
   * Returns the value of the '<em><b>Characteristic</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Characteristic</em>' reference.
   * @see #setCharacteristic(Characteristic)
   * @see xtext.featurelanguage.featureLanguage.FeatureLanguagePackage#getConstraint_Characteristic()
   * @model
   * @generated
   */
  Characteristic getCharacteristic();

  /**
   * Sets the value of the '{@link xtext.featurelanguage.featureLanguage.Constraint#getCharacteristic <em>Characteristic</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Characteristic</em>' reference.
   * @see #getCharacteristic()
   * @generated
   */
  void setCharacteristic(Characteristic value);

  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference list.
   * The list contents are of type {@link xtext.featurelanguage.featureLanguage.Condition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference list.
   * @see xtext.featurelanguage.featureLanguage.FeatureLanguagePackage#getConstraint_Condition()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getCondition();

  /**
   * Returns the value of the '<em><b>Errormsg</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Errormsg</em>' attribute list.
   * @see xtext.featurelanguage.featureLanguage.FeatureLanguagePackage#getConstraint_Errormsg()
   * @model unique="false"
   * @generated
   */
  EList<String> getErrormsg();

} // Constraint
