/*
 * generated by Xtext 2.32.0
 */
package xtext.featurelanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FeatureLanguageUiModule extends AbstractFeatureLanguageUiModule {

	public FeatureLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
