/**
 * generated by Xtext 2.32.0
 */
package my.xtext.featurelist.myfeaturelist.myFeatureList.impl;

import my.xtext.featurelist.myfeaturelist.myFeatureList.ConceptProperty;
import my.xtext.featurelist.myfeaturelist.myFeatureList.MyFeatureListPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Concept Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ConceptPropertyImpl extends PropertyImpl implements ConceptProperty
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConceptPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyFeatureListPackage.Literals.CONCEPT_PROPERTY;
  }

} //ConceptPropertyImpl
